### PR TITLE
Windows tweaks and fixes

### PR DESCRIPTION
**Pull request by dra27**
I'm presently running this through all 6 Windows ports (they all build using bootstrapping, so it's testing that too).

My git clones always use Windows checkouts (core.autocrlf = true) which tests unexpected things. To me, this doesn't have to be right before merging, I can fix it further during the release cycle as it affects developers only (since our tarball releases always use Unix line endings).

The big fix here is that set-up of `ocamltest_config.ml` which was generating /cygdrive paths for the native Windows ports.

There is a temporary commit which removes the use of `sed` - this normalisation I think is flawed. In my setup, for example, the reference files have Windows line endings and so this "normalisation" breaks an otherwise OK comparison. This needs some more thought on a proper solution (in the long term, not using cmp, I guess, as it will be more portable)

### CODE REVIEW

**Comment by shindere** [comment]
I integrated the critical modifications to the branch directly, i.e.
make compilation of ocamltest work when flexlink is bootstrapped and the
calculation of ocamlsrcdir under Windows.

Am I correct in assuming than the rest (including the change in
git-attributes) can be postponed to after the merge?

**Comment by dra27** [comment]
The .gitattributes would be handy, just because it's a nuisance when there's a bash script which doesn't have the line endings declared, but it's not critical, no.

**Comment by shindere** [comment]
David Allsopp (2017/09/15 14:18 +0000):
> The .gitattributes would be handy,

It's in! :)

**Comment by dra27** [comment]
Thank you :)

**Comment by shindere** [comment]
David Allsopp (2017/09/15 15:05 +0000):
> Thank you :)

My pleasure!

**Pull request closed without merging**
